### ISSUE TITLE
Project 组件的一些问题

### ISSUE THREAD

**Issue by KuTuGu** [Muxi-X/muxi_workbench_fe#2]
- 新建项目：1、空白输入没有提示；2、页面内返回不是返回项目主界面；3、项目描述是选填，但是不填就无法创建项目；4、点击输入栏之后提示语没有消失，键盘输入才消失；
- 项目-查看项目-上传文件：1、下拉列表框出现后鼠标点击其他位置不能收起；2、没有上传结果反馈，失败没有提示(如图片体积过大没有提示)
- 项目-移动/删除已存在的某个文件夹：1、有时鼠标放在文件夹上，“移动、删除”会出现一下又消失，导致不好操作。能否换用鼠标右键进行操作？
- 项目-查看项目-查看成员：1、成员排版；2、成员人数错误；3、名称过长没有滚动条；4、无成员没有提示
- 项目-查看项目-回收站：1、创建删除时间不对
- 设置项目后返回到 /project/${proID}/preview 后，界面空白(现在是返回到/project)
- select组件的 onchange 函数模糊，/src/components/common/select/index.jsx

**Comment by Zendq1998** [comment]
[新建分支改bug](https://github.com/Muxi-X/muxi_workbench_fe/commit/b3543ddf9b9872059cc67be31be3b364f9e19add)
- 新建项目：
    - [x] 空白输入没有提示
    - [x] 页面内返回不是返回项目主界面（按照设计稿用取消）
    - [x] 项目描述是选填，但是不填就无法创建项目
    - [x] 点击输入栏之后提示语没有消失，键盘输入才消失 （茅心雨说不是大问题，不用改了）
- 项目-查看项目-上传文件：
    - [ ] 下拉列表框出现后鼠标点击其他位置不能收起
    - [ ]  没有上传结果反馈，失败没有提示(如图片体积过大没有提示)
- 项目-移动/删除已存在的某个文件夹：
    - [x] 有时鼠标放在文件夹上，“移动、删除”会出现一下又消失，导致不好操作。能否换用鼠标右键进行操作？(**我认为右键不太好，调大了鼠标 hover 的范围，左右留 20px，底部留 10px**)
- 项目-查看项目-查看成员：
    - [x] 成员排版
    - [x] 成员人数错误 (之后新建的都没有问题了)**编辑成员之后再请求人数信息不变** @Darren2017 
    - [x] 名称过长没有滚动条
    - [x] 无成员没有提示
- 项目-查看项目-回收站：
    - [x] 创建删除时间不对
- [x] 设置项目后返回到 /project/${proID}/preview 后，界面空白(现在是返回到/project)
- [x] （在组件文档中加了一点信息，有问题可以跟我说）select组件的 onchange 函数模糊，/src/components/common/select/index.jsx

**Comment by Darren2017** [comment]
这么优秀的吗…
什么时候可以重新部署啊
在 2019年2月16日 +0800 18:13，曾德勤 <notifications@github.com>，写道：
